# ------------------------------------- #
# ---- General Settings --------------- #
# ------------------------------------- #
baseURL = "https://stoneworld.github.io/"
title = "流水当歌醉，落叶亦芳菲"
theme = "hugo-theme-den"
enableRobotsTXT = true      # generate robots.txt
enableEmoji = true           # use emoji support
hasCJKLanguage = true        # detect CJK languages for word count etc.
preserveTaxonomyNames = true # do not make tag names lowercase
# uglyURLs = true            # more info: https://gohugo.io/content-management/urls/#ugly-urls
rssLimit = 100                # limit number of entries in RSS feeds
page_view_conter = true

# Copyright, appears in the footer
# copyright = ""             # default: author.name

# Pagination
# number of entries per page for archives, tags and categories
# since we don't have list view, recommend a large value
paginate = 20
paginatePath = "page"

# Syntax Hightlight
PygmentsCodeFences = true
PygmentsUseClasses = true    # required for shhighlight shortcode

# service plugins
disqusShortname = ""         # disqus_shortname
googleAnalytics = ""         # UA-XXXXXXXX-X

# language support # en / zh / other... translations present in i18n/
defaultContentLanguage = "zh"           # Default language to use
defaultContentLanguageInSubdir = true

# Links format
[permalinks]
  posts = "/:year/:month/:day/:filename/"
  categories = "/category/:slug/"      # required
  tags = "/tag/:slug/"                # required
  pages = "/:slug/"

[author]                     # required
  name = "Wang Shuai"

[sitemap]                    # required
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# ------------------------------------- #
# ---- Other Params ------------------- #
# ------------------------------------- #

[params]
  since = "2020"             # Site creation time
  rssFullContent = true      # set true to use full content instead of summary

  # site info (optional)
  keywords = ["hugo","blockchain","programming"]
  description = "Blockchain | Programming | Photography | Go"
  logoTitle = "stoneworld" # shown on top-left, default: title
  siteLogoImage = "images/globe.svg"     # shown besides logoTitle
  # headerTitle = "stoneworld"                   # default: title
  headerImage = "images/background.webp"
  showAuthorCard = true # Whether to show author information below the article

  autoLoadComments = false # auto load comment when scrolling down

  # paginate style, default use numbered pagination links
  # if true, use original "Previous" and "Next" links.
  paginateOriginalStyle = true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  google_verification = ""  # Google_Verification

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = ['custom.css']             # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []              # if ['custom.js'], load '/static/js/custom.js' file

  [markup]
      [markup.goldmark]
        [markup.goldmark.renderer]
          unsafe = true

# ------------------------------------- #
# ---- Related Articles --------------- #
# ------------------------------------- #
[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 50

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = true

  # Will lower case keywords in both queries and in the indexes.
  toLower = true

[[related.indices]]
  name = "categories"
  weight = 200

[[related.indices]]
  name = "keywords"
  weight = 150

[[related.indices]]
  name = "tags"
  weight = 100


  [languages.zh]
  languageCode = "zh"
  languageName = "中文"
  contentDir = "content/zh"
  weight = 1

  [languages.zh.params]
    description = "Blockchain | Programming | Photography | Go"

  [[languages.zh.menu.main]]
    name = "思考"
    weight = 10
    identifier = "ideas"
    url = "category/ideas/"
  [[languages.zh.menu.main]]
    name = "工具"
    weight = 20
    identifier = "tools"
    url = "category/tools/"
  [[languages.zh.menu.main]]
    name = "编程"
    weight = 30
    identifier = "develop"
    url = "category/develop/"
  [[languages.zh.menu.links]]
    name = " GitHub"
    weight = 10
    identifier = "github"
    url = "https://github.com/stoneworld"